(prelude-require-packages
 '(bookmark+
   clojure-mode
   cider
   coffee-mode
   haml-mode
   idle-highlight-mode
   paredit
   rainbow-delimiters
   rainbow-mode
   saveplace
   sass-mode
   smex
   yaml-mode))
